services:
  splunk:
    platform: linux/amd64
    image: splunk/splunk:latest
    container_name: splunk
    environment:
      - SPLUNK_GENERAL_TERMS=--accept-sgt-current-at-splunk-com
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=password
    ports:
      - "8000:8000"
      - "8088:8088"
      - "8089:8089"
    volumes:
      - splunk-etc:/opt/splunk/etc
      - splunk-var:/opt/splunk/var

  opensearch:
    image: opensearchproject/opensearch:2.11.0
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - DISABLE_SECURITY_PLUGIN=true
    ports:
      - "9200:9200"
      - "9600:9600"
    volumes:
      - opensearch-data:/usr/share/opensearch/data

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.11.0
    container_name: opensearch-dashboards
    ports:
      - "5601:5601"
    environment:
      OPENSEARCH_HOSTS: '["http://opensearch:9200"]'
      DISABLE_SECURITY_DASHBOARDS_PLUGIN: "true"
    depends_on:
      - opensearch

  ssh-server:
    image: linuxserver/openssh-server
    container_name: ssh-server
    ports:
      - "2222:2222"
    volumes:
      - ./ssh/authorized_keys:/config/authorized_keys:rw
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - USER_NAME=testuser
      - PUBLIC_KEY_FILE=/config/authorized_keys

  k3s-server:
    image: rancher/k3s:v1.28.2-k3s1
    container_name: k3s-server
    privileged: true
    ports:
      - "6443:6443"
    volumes:
      - k3s-data:/var/lib/rancher/k3s
    command: server --disable traefik --write-kubeconfig-mode 644

  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"            # LocalStack Gateway
      - "4510-4559:4510-4559"  # External services
    environment:
      - SERVICES=logs
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - localstack-data:/var/lib/localstack
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  splunk-etc:
  splunk-var:
  opensearch-data:
  k3s-data:
  localstack-data:
