services:
  splunk:
    platform: linux/amd64
    image: splunk/splunk:latest
    container_name: splunk
    environment:
      - SPLUNK_GENERAL_TERMS=--accept-sgt-current-at-splunk-com
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=password
    ports:
      - "8000:8000"
      - "8088:8088"
      - "8089:8089"
    volumes:
      - splunk-etc:/opt/splunk/etc
      - splunk-var:/opt/splunk/var

volumes:
  splunk-etc:
    driver: local
  splunk-var:
    driver: local
